export interface CountryItem {
  code: string;
  name: string;
  flag: string;
  dial: string;
}

export const COUNTRIES: CountryItem[] = [
  { code: "DZ", name: "Algérie", flag: "🇩🇿", dial: "+213" },
  { code: "AO", name: "Angola", flag: "🇦🇴", dial: "+244" },
  { code: "BJ", name: "Bénin", flag: "🇧🇯", dial: "+229" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", dial: "+267" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", dial: "+226" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", dial: "+257" },
  { code: "CM", name: "Cameroun", flag: "🇨🇲", dial: "+237" },
  { code: "CV", name: "Cap-Vert", flag: "🇨🇻", dial: "+238" },
  { code: "CF", name: "Centrafrique", flag: "🇨🇫", dial: "+236" },
  { code: "KM", name: "Comores", flag: "🇰🇲", dial: "+269" },
  { code: "CG", name: "Congo", flag: "🇨🇬", dial: "+242" },
  { code: "CD", name: "Congo (RDC)", flag: "🇨🇩", dial: "+243" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", dial: "+225" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", dial: "+253" },
  { code: "EG", name: "Égypte", flag: "🇪🇬", dial: "+20" },
  { code: "ER", name: "Érythrée", flag: "🇪🇷", dial: "+291" },
  { code: "ET", name: "Éthiopie", flag: "🇪🇹", dial: "+251" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", dial: "+241" },
  { code: "GM", name: "Gambie", flag: "🇬🇲", dial: "+220" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", dial: "+233" },
  { code: "GN", name: "Guinée", flag: "🇬🇳", dial: "+224" },
  { code: "GW", name: "Guinée-Bissau", flag: "🇬🇼", dial: "+245" },
  { code: "GQ", name: "Guinée équatoriale", flag: "🇬🇶", dial: "+240" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", dial: "+254" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", dial: "+266" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", dial: "+231" },
  { code: "LY", name: "Libye", flag: "🇱🇾", dial: "+218" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", dial: "+261" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", dial: "+265" },
  { code: "ML", name: "Mali", flag: "🇲🇱", dial: "+223" },
  { code: "MA", name: "Maroc", flag: "🇲🇦", dial: "+212" },
  { code: "MR", name: "Mauritanie", flag: "🇲🇷", dial: "+222" },
  { code: "MU", name: "Maurice", flag: "🇲🇺", dial: "+230" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", dial: "+258" },
  { code: "NA", name: "Namibie", flag: "🇳🇦", dial: "+264" },
  { code: "NE", name: "Niger", flag: "🇳🇪", dial: "+227" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", dial: "+234" },
  { code: "UG", name: "Ouganda", flag: "🇺🇬", dial: "+256" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", dial: "+250" },
  { code: "ST", name: "São Tomé-et-Príncipe", flag: "🇸🇹", dial: "+239" },
  { code: "SN", name: "Sénégal", flag: "🇸🇳", dial: "+221" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", dial: "+248" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", dial: "+232" },
  { code: "SO", name: "Somalie", flag: "🇸🇴", dial: "+252" },
  { code: "SD", name: "Soudan", flag: "🇸🇩", dial: "+249" },
  { code: "SS", name: "Soudan du Sud", flag: "🇸🇸", dial: "+211" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", dial: "+268" },
  { code: "TZ", name: "Tanzanie", flag: "🇹🇿", dial: "+255" },
  { code: "TD", name: "Tchad", flag: "🇹🇩", dial: "+235" },
  { code: "TG", name: "Togo", flag: "🇹🇬", dial: "+228" },
  { code: "TN", name: "Tunisie", flag: "🇹🇳", dial: "+216" },
  { code: "ZM", name: "Zambie", flag: "🇿🇲", dial: "+260" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", dial: "+263" },
  // International
  { code: "FR", name: "France", flag: "🇫🇷", dial: "+33" },
  { code: "BE", name: "Belgique", flag: "🇧🇪", dial: "+32" },
  { code: "CA", name: "Canada", flag: "🇨🇦", dial: "+1" },
  { code: "CH", name: "Suisse", flag: "🇨🇭", dial: "+41" },
  { code: "US", name: "États-Unis", flag: "🇺🇸", dial: "+1" },
  { code: "GB", name: "Royaume-Uni", flag: "🇬🇧", dial: "+44" },
  { code: "DE", name: "Allemagne", flag: "🇩🇪", dial: "+49" },
  { code: "BR", name: "Brésil", flag: "🇧🇷", dial: "+55" },
  { code: "AE", name: "Émirats Arabes", flag: "🇦🇪", dial: "+971" },
];
